### ISSUE TITLE
FINGERPRINT_PERMISSION_DENIED, FINGERPRINT_NOT_SUPPORTED and FINGERPRINT_REGISTRATION_NEEDED is misused.

### ISSUE THREAD

**Issue by TonyTangAndroid** [aitorvs/fingerlock#1]
`
@Override
    public boolean isFingerprintAuthSupported() {
        invalidContext();

        // check permissions
        int granted = ContextCompat.checkSelfPermission(mContext, android.Manifest.permission.USE_FINGERPRINT);
        if (granted != PackageManager.PERMISSION_GRANTED) {
            // not granted
            return false;
        }

        // return hardware support
        //noinspection MissingPermission
        return mFingerprintManager != null
                && mFingerprintManager.isHardwareDetected()
                && mFingerprintManager.hasEnrolledFingerprints();

    }
`

Currently,

FINGERPRINT_PERMISSION_DENIED and FINGERPRINT_REGISTRATION_NEEDED will also return FINGERPRINT_NOT_SUPPORTED, which is misleading.

**Comment by aitorvs** [comment]
Yes, good catch. It is fixed already for the next release.
