### ISSUE TITLE
Update the Docs 

### ISSUE THREAD

**Issue by amineMpdam** [aitorvs/fingerlock#3]
Hey, great library !!
if possible can you update the the doc with an example with a fragment, because after a little looking around in the source files of the lib the method initialize takes only an AppCompatActivity as a parameter.

**Comment by aitorvs** [comment]
The lib currently only supports activities as host. Extending support to fragments is something I want to do but haven't had the time yet.
I also accept PRs if you want to give it a try.

**Comment by amineMpdam** [comment]
Sure, i've been working on it lately, and i'll sent Pull rquest as soon as i complete testing.
