### ISSUE TITLE
Galaxy s5 "Fingerprint authentication not supported in this device" 

### ISSUE THREAD

**Issue by crockkaw** [aitorvs/fingerlock#4]
Hi
I tried this app on my Samsung Galaxy S5 (SM-G900F) with Android 6.0.1. This device is equipped with fingerprint scaner. 
I have defined fingerprints and I use this method to unlock my lock screen. 
I have tried to use other app like "Finger Security" and it's working normally. 

But when I try to use this app I get this message "Fingerprint authentication not supported in this device"  
What can I do to make this app work?

**Comment by aitorvs** [comment]
To my knowledge Samsung S5 does not support Android M fingerprint API. Samsung provides their own API for fingerprint.
